"""auth sessions audit processing status review events

Revision ID: 49d02ffb0de5
Revises: cfaabfd2cf75
Create Date: 2026-09-26 17:52:57.344043

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49d02ffb0de5"
down_revision: str | Sequence[str] | None = "cfaabfd2cf75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_index("ix_auth_sessions_user_id", "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_audit_events_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_patient_created", "audit_events", ["patient_id", "created_at"], unique=False
    )
    op.add_column("alert_events", sa.Column("from_status", sa.String(length=16), nullable=True))
    op.add_column("alert_events", sa.Column("to_status", sa.String(length=16), nullable=True))
    op.execute("UPDATE alert_events SET to_status = 'OPEN' WHERE action = 'CREATED'")
    op.alter_column("alert_events", "to_status", nullable=False)
    op.add_column("alert_events", sa.Column("request_key", sa.Uuid(), nullable=True))
    op.add_column("alert_events", sa.Column("request_sha256", sa.String(length=64), nullable=True))
    op.create_check_constraint(
        op.f("ck_alert_events_request_key_iff_human"),
        "alert_events",
        "(action = 'CREATED') = (request_key IS NULL)",
    )
    op.create_index("ix_alert_events_alert_created", "alert_events", ["alert_id", "created_at"], unique=False)
    op.create_unique_constraint(
        "uq_alert_events_alert_request_key", "alert_events", ["alert_id", "request_key"]
    )
    op.add_column(
        "alerts", sa.Column("lock_version", sa.Integer(), server_default=sa.text("1"), nullable=False)
    )
    op.alter_column("analyses", "forecast_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("analyses", "model_version_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("analyses", "policy_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("analyses", "comparability_key", existing_type=sa.VARCHAR(length=160), nullable=True)
    op.add_column("assessments", sa.Column("processing_status", sa.String(length=16), nullable=True))
    # Existing receipts: finished unless their analysis is still retryable.
    op.execute(
        "UPDATE assessments SET processing_status = CASE "
        "WHEN analysis_state = 'ANALYSIS_ERROR' THEN 'FAILED' "
        "WHEN analysis_state = 'PENDING' THEN 'RECEIVED' ELSE 'ANALYZED' END"
    )
    op.alter_column("assessments", "processing_status", nullable=False)
    op.create_check_constraint(
        op.f("ck_assessments_processing_status_valid"),
        "assessments",
        "processing_status IN ('RECEIVED', 'ANALYZED', 'FAILED')",
    )
    # Every submitted assessment now has an analysis row (guide 05 §9); backfill terminal ones.
    op.execute(
        "INSERT INTO analyses (id, assessment_id, session_id, patient_id, slot_index, availability, reasons, attempts) "
        "SELECT gen_random_uuid(), a.id, a.session_id, a.patient_id, a.slot_index, a.analysis_state, "
        "a.analysis_reasons, 0 FROM assessments a "
        "WHERE NOT EXISTS (SELECT 1 FROM analyses x WHERE x.assessment_id = a.id)"
    )
    op.create_check_constraint(
        op.f("ck_analyses_forecast_link_all_or_none"),
        "analyses",
        "(forecast_id IS NULL) = (model_version_id IS NULL) AND (forecast_id IS NULL) = (policy_id IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_analyses_complete_needs_forecast"),
        "analyses",
        "availability <> 'COMPLETE' OR forecast_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_analyses_complete_needs_forecast"), "analyses", type_="check")
    op.drop_constraint(op.f("ck_analyses_forecast_link_all_or_none"), "analyses", type_="check")
    # Downgrade removes only the forecast-less rows this migration's contract introduced.
    op.execute("DELETE FROM analyses WHERE forecast_id IS NULL")
    op.drop_constraint(op.f("ck_assessments_processing_status_valid"), "assessments", type_="check")
    op.drop_column("assessments", "processing_status")
    op.alter_column("analyses", "comparability_key", existing_type=sa.VARCHAR(length=160), nullable=False)
    op.alter_column("analyses", "policy_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("analyses", "model_version_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("analyses", "forecast_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("alerts", "lock_version")
    op.drop_constraint("uq_alert_events_alert_request_key", "alert_events", type_="unique")
    op.drop_index("ix_alert_events_alert_created", table_name="alert_events")
    op.drop_constraint(op.f("ck_alert_events_request_key_iff_human"), "alert_events", type_="check")
    op.drop_column("alert_events", "request_sha256")
    op.drop_column("alert_events", "request_key")
    op.drop_column("alert_events", "to_status")
    op.drop_column("alert_events", "from_status")
    op.drop_index("ix_audit_events_patient_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_auth_sessions_user_id", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    # ### end Alembic commands ###
