"""scope submission keys per patient

Revision ID: 5f30ee0bced4
Revises: 49d02ffb0de5
Create Date: 2026-09-26 18:06:14.332976

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f30ee0bced4"
down_revision: str | Sequence[str] | None = "49d02ffb0de5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_assessments_submission_key"), "assessments", type_="unique")
    op.create_unique_constraint(
        "uq_assessments_patient_submission_key", "assessments", ["patient_id", "submission_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_assessments_patient_submission_key", "assessments", type_="unique")
    op.create_unique_constraint(
        op.f("uq_assessments_submission_key"),
        "assessments",
        ["submission_key"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
