"""assessment sessions assessments context

Revision ID: b6a95bb0a030
Revises: 5482f01f0059
Create Date: 2026-09-26 16:19:46.138222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6a95bb0a030"
down_revision: str | Sequence[str] | None = "5482f01f0059"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("start_key", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("protocol_version", sa.String(length=64), nullable=False),
        sa.Column("scoring_version", sa.String(length=64), nullable=False),
        sa.Column("input_mode", sa.String(length=16), nullable=False),
        sa.Column("schedule_purpose", sa.String(length=32), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("target_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_state", sa.String(length=32), nullable=False),
        sa.Column("forecast_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("history_cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("protocol_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "forecast_state IN ('READY', 'BUILDING_BASELINE', 'INSUFFICIENT_DATA', 'MODEL_UNAVAILABLE')",
            name=op.f("ck_assessment_sessions_forecast_state_valid"),
        ),
        sa.CheckConstraint(
            "input_mode IN ('keyboard', 'pointer')", name=op.f("ck_assessment_sessions_input_mode_valid")
        ),
        sa.CheckConstraint(
            "schedule_purpose IN ('SCHEDULED', 'RETAKE_AFTER_UNRELIABLE', 'EXTRA_ATTEMPT', 'OFF_SCHEDULE')",
            name=op.f("ck_assessment_sessions_schedule_purpose_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('LIVE_DEMO', 'SYNTHETIC_HISTORY', 'SCENARIO_REPLAY')",
            name=op.f("ck_assessment_sessions_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('STARTED', 'SUBMITTED', 'ABANDONED', 'EXPIRED')",
            name=op.f("ck_assessment_sessions_status_valid"),
        ),
        sa.CheckConstraint("expires_at > started_at", name=op.f("ck_assessment_sessions_expiry_after_start")),
        sa.CheckConstraint("slot_index >= 0", name=op.f("ck_assessment_sessions_slot_index_nonnegative")),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_assessment_sessions_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_sessions")),
        sa.UniqueConstraint("patient_id", "start_key", name="uq_assessment_sessions_patient_start_key"),
    )
    op.create_index(
        "ix_assessment_sessions_patient_slot",
        "assessment_sessions",
        ["patient_id", "slot_index"],
        unique=False,
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("submission_key", sa.Uuid(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("protocol_version", sa.String(length=64), nullable=False),
        sa.Column("scoring_version", sa.String(length=64), nullable=False),
        sa.Column("raw_responses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("memory_score", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("attention_score", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("reaction_time_ms", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("quality", sa.String(length=16), nullable=False),
        sa.Column("quality_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("longitudinal_eligible", sa.Boolean(), nullable=False),
        sa.Column("schedule_purpose", sa.String(length=32), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("target_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("analysis_state", sa.String(length=32), nullable=False),
        sa.Column("analysis_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "analysis_state IN ('PENDING', 'BUILDING_BASELINE', 'INSUFFICIENT_DATA', 'MODEL_UNAVAILABLE', 'ANALYSIS_ERROR', 'COMPLETE')",
            name=op.f("ck_assessments_analysis_state_valid"),
        ),
        sa.CheckConstraint(
            "quality IN ('VALID', 'LOW', 'INCOMPLETE')", name=op.f("ck_assessments_quality_valid")
        ),
        sa.CheckConstraint(
            "schedule_purpose IN ('SCHEDULED', 'RETAKE_AFTER_UNRELIABLE', 'EXTRA_ATTEMPT', 'OFF_SCHEDULE')",
            name=op.f("ck_assessments_schedule_purpose_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('LIVE_DEMO', 'SYNTHETIC_HISTORY', 'SCENARIO_REPLAY')",
            name=op.f("ck_assessments_source_valid"),
        ),
        sa.CheckConstraint(
            "attention_score BETWEEN 0 AND 100", name=op.f("ck_assessments_attention_score_range")
        ),
        sa.CheckConstraint("memory_score BETWEEN 0 AND 100", name=op.f("ck_assessments_memory_score_range")),
        sa.CheckConstraint(
            "reaction_time_ms >= 100 AND reaction_time_ms < 3000",
            name=op.f("ck_assessments_reaction_time_range"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_assessments_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["assessment_sessions.id"],
            name=op.f("fk_assessments_session_id_assessment_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint("session_id", name=op.f("uq_assessments_session_id")),
        sa.UniqueConstraint("submission_key", name=op.f("uq_assessments_submission_key")),
    )
    op.create_index("ix_assessments_patient_slot", "assessments", ["patient_id", "slot_index"], unique=False)
    op.create_index(
        "uq_assessments_representative_per_slot",
        "assessments",
        ["patient_id", "slot_index"],
        unique=True,
        postgresql_where=sa.text("longitudinal_eligible"),
    )
    op.create_table(
        "context_checkins",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("sleep_hours", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("mood_score", sa.SmallInteger(), nullable=True),
        sa.Column("medication_change", sa.String(length=16), nullable=True),
        sa.Column("reported_by", sa.String(length=24), nullable=False),
        sa.Column("missing_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "medication_change IN ('YES', 'NO', 'NOT_SURE')",
            name=op.f("ck_context_checkins_medication_change_valid"),
        ),
        sa.CheckConstraint(
            "reported_by IN ('PATIENT', 'CAREGIVER_ASSISTED')",
            name=op.f("ck_context_checkins_reported_by_valid"),
        ),
        sa.CheckConstraint("mood_score BETWEEN 1 AND 10", name=op.f("ck_context_checkins_mood_score_range")),
        sa.CheckConstraint(
            "sleep_hours BETWEEN 0 AND 24", name=op.f("ck_context_checkins_sleep_hours_range")
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_context_checkins_assessment_id_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_context_checkins_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_checkins")),
        sa.UniqueConstraint("assessment_id", name=op.f("uq_context_checkins_assessment_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("context_checkins")
    op.drop_index(
        "uq_assessments_representative_per_slot",
        table_name="assessments",
        postgresql_where=sa.text("longitudinal_eligible"),
    )
    op.drop_index("ix_assessments_patient_slot", table_name="assessments")
    op.drop_table("assessments")
    op.drop_index("ix_assessment_sessions_patient_slot", table_name="assessment_sessions")
    op.drop_table("assessment_sessions")
    # ### end Alembic commands ###
