"""forecasting registry forecasts analyses alerts

Revision ID: cfaabfd2cf75
Revises: b6a95bb0a030
Create Date: 2026-09-26 17:21:30.902921

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cfaabfd2cf75"
down_revision: str | Sequence[str] | None = "b6a95bb0a030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Composite-FK targets must exist before the tables that reference them.
    op.create_unique_constraint(
        "uq_assessment_sessions_id_patient", "assessment_sessions", ["id", "patient_id"]
    )
    op.create_unique_constraint(
        "uq_assessments_id_session_patient", "assessments", ["id", "session_id", "patient_id"]
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=False),
        sa.Column("preprocessing_version", sa.String(length=64), nullable=False),
        sa.Column("postprocessing_version", sa.String(length=64), nullable=False),
        sa.Column("artifact_relative_path", sa.String(length=512), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("feature_order", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sequence_length", sa.Integer(), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("activatable", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('LAST_VALUE', 'LINEAR_TREND', 'GRU')", name=op.f("ck_model_versions_kind_valid")
        ),
        sa.CheckConstraint(
            "NOT is_active OR activatable", name=op.f("ck_model_versions_active_requires_activatable")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_model_versions_version")),
    )
    op.create_index(
        "uq_model_versions_single_active",
        "model_versions",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "anomaly_policies",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("policy_schema_version", sa.String(length=64), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calibration_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("activatable", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "NOT is_active OR activatable", name=op.f("ck_anomaly_policies_active_requires_activatable")
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_anomaly_policies_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomaly_policies")),
        sa.UniqueConstraint("id", "model_version_id", name="uq_anomaly_policies_id_model"),
        sa.UniqueConstraint("version", name=op.f("uq_anomaly_policies_version")),
    )
    op.create_index(
        "uq_anomaly_policies_single_active",
        "anomaly_policies",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("target_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("history_cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predicted_memory_score", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("predicted_attention_score", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("predicted_reaction_time_ms", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("bounds_applied", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_assessment_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("feature_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("feature_sha256", sa.String(length=64), nullable=False),
        sa.Column("comparability_key", sa.String(length=160), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=False),
        sa.Column("preprocessing_version", sa.String(length=64), nullable=False),
        sa.Column("postprocessing_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "issued_at <= history_cutoff_at + interval '1 minute'", name=op.f("ck_forecasts_issued_at_cutoff")
        ),
        sa.CheckConstraint(
            "predicted_attention_score BETWEEN 0 AND 100", name=op.f("ck_forecasts_attention_range")
        ),
        sa.CheckConstraint(
            "predicted_memory_score BETWEEN 0 AND 100", name=op.f("ck_forecasts_memory_range")
        ),
        sa.CheckConstraint(
            "predicted_reaction_time_ms >= 100 AND predicted_reaction_time_ms <= 2999.999",
            name=op.f("ck_forecasts_rt_range"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_id", "model_version_id"],
            ["anomaly_policies.id", "anomaly_policies.model_version_id"],
            name="fk_forecasts_policy_model",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "patient_id"],
            ["assessment_sessions.id", "assessment_sessions.patient_id"],
            name="fk_forecasts_session_patient",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecasts")),
        sa.UniqueConstraint(
            "id", "session_id", "patient_id", "model_version_id", "policy_id", name="uq_forecasts_identity"
        ),
        sa.UniqueConstraint("session_id", name=op.f("uq_forecasts_session_id")),
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("forecast_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("comparability_key", sa.String(length=160), nullable=False),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deviation_level", sa.String(length=32), nullable=True),
        sa.Column("domain_deviations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("max_deviation", sa.Double(), nullable=True),
        sa.Column("aggregate_deviation", sa.Double(), nullable=True),
        sa.Column("moderate_signal", sa.Boolean(), nullable=True),
        sa.Column("high_signal", sa.Boolean(), nullable=True),
        sa.Column("persistent_count", sa.Integer(), nullable=True),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("explanation_version", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(availability = 'COMPLETE') = (deviation_level IS NOT NULL)",
            name=op.f("ck_analyses_level_iff_complete"),
        ),
        sa.CheckConstraint(
            "availability IN ('PENDING', 'BUILDING_BASELINE', 'INSUFFICIENT_DATA', 'MODEL_UNAVAILABLE', 'ANALYSIS_ERROR', 'COMPLETE')",
            name=op.f("ck_analyses_availability_valid"),
        ),
        sa.CheckConstraint(
            "deviation_level IS NULL OR deviation_level IN ('NORMAL', 'REVIEW', 'PERSISTENT_DEVIATION', 'HIGH_DEVIATION')",
            name=op.f("ck_analyses_deviation_level_valid"),
        ),
        sa.CheckConstraint(
            "persistent_count IS NULL OR persistent_count >= 0",
            name=op.f("ck_analyses_persistent_count_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "session_id", "patient_id"],
            ["assessments.id", "assessments.session_id", "assessments.patient_id"],
            name="fk_analyses_assessment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["forecast_id", "session_id", "patient_id", "model_version_id", "policy_id"],
            [
                "forecasts.id",
                "forecasts.session_id",
                "forecasts.patient_id",
                "forecasts.model_version_id",
                "forecasts.policy_id",
            ],
            name="fk_analyses_forecast",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
        sa.UniqueConstraint("assessment_id", name=op.f("uq_analyses_assessment_id")),
        sa.UniqueConstraint("id", "patient_id", name="uq_analyses_id_patient"),
    )
    op.create_index(
        "ix_analyses_patient_availability", "analyses", ["patient_id", "availability"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("deviation_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "deviation_level IN ('REVIEW', 'PERSISTENT_DEVIATION', 'HIGH_DEVIATION')",
            name=op.f("ck_alerts_level_not_normal"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')", name=op.f("ck_alerts_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
            name=op.f("fk_alerts_acknowledged_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id", "patient_id"],
            ["analyses.id", "analyses.patient_id"],
            name="fk_alerts_analysis_patient",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_alerts_assessment_id_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name=op.f("fk_alerts_resolved_by_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("analysis_id", name=op.f("uq_alerts_analysis_id")),
        sa.UniqueConstraint("assessment_id", name=op.f("uq_alerts_assessment_id")),
    )
    op.create_index("ix_alerts_patient_status", "alerts", ["patient_id", "status"], unique=False)
    op.create_table(
        "alert_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "action IN ('CREATED', 'ACKNOWLEDGED', 'NOTE_ADDED', 'RESOLVED')",
            name=op.f("ck_alert_events_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_alert_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name=op.f("fk_alert_events_alert_id_alerts"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_events")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alert_events")
    op.drop_index("ix_alerts_patient_status", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_analyses_patient_availability", table_name="analyses")
    op.drop_table("analyses")
    op.drop_table("forecasts")
    op.drop_index(
        "uq_anomaly_policies_single_active",
        table_name="anomaly_policies",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("anomaly_policies")
    op.drop_index(
        "uq_model_versions_single_active", table_name="model_versions", postgresql_where=sa.text("is_active")
    )
    op.drop_table("model_versions")
    op.drop_constraint("uq_assessments_id_session_patient", "assessments", type_="unique")
    op.drop_constraint("uq_assessment_sessions_id_patient", "assessment_sessions", type_="unique")
    # ### end Alembic commands ###
